import { createEnv } from '@t3-oss/env-nextjs';
import { z } from 'zod';
import { optionalBooleanString, optionalString, optionalUrl } from './utils';

export const clientEnv = createEnv({
  client: {
    // Application
    NEXT_PUBLIC_BASE_URL: z.string().url(),
    NEXT_PUBLIC_PAYMENT_PROVIDER: z.enum(['stripe', 'creem']),

    // Payment - Stripe Prices
    NEXT_PUBLIC_STRIPE_PRICE_PRO_MONTHLY: optionalString,
    NEXT_PUBLIC_STRIPE_PRICE_PRO_YEARLY: optionalString,
    NEXT_PUBLIC_STRIPE_PRICE_LIFETIME: optionalString,
    NEXT_PUBLIC_STRIPE_PRICE_CREDITS_BASIC: optionalString,
    NEXT_PUBLIC_STRIPE_PRICE_CREDITS_STANDARD: optionalString,
    NEXT_PUBLIC_STRIPE_PRICE_CREDITS_PREMIUM: optionalString,
    NEXT_PUBLIC_STRIPE_PRICE_CREDITS_ENTERPRISE: optionalString,

    // Payment - Creem Products
    NEXT_PUBLIC_CREEM_PRODUCT_PRO_MONTHLY: optionalString,
    NEXT_PUBLIC_CREEM_PRODUCT_PRO_YEARLY: optionalString,
    NEXT_PUBLIC_CREEM_PRODUCT_LIFETIME: optionalString,
    NEXT_PUBLIC_CREEM_PRODUCT_CREDITS_BASIC: optionalString,
    NEXT_PUBLIC_CREEM_PRODUCT_CREDITS_STANDARD: optionalString,
    NEXT_PUBLIC_CREEM_PRODUCT_CREDITS_PREMIUM: optionalString,
    NEXT_PUBLIC_CREEM_PRODUCT_CREDITS_ENTERPRISE: optionalString,

    // Feature Flags
    NEXT_PUBLIC_DEMO_WEBSITE: optionalBooleanString,
    NEXT_PUBLIC_ENABLE_CREDITS: optionalBooleanString,
    NEXT_PUBLIC_ENABLE_ANALYTICS_IN_DEV: optionalBooleanString,

    // Analytics - Google
    NEXT_PUBLIC_GOOGLE_ANALYTICS_ID: optionalString,
    // Analytics - Umami
    NEXT_PUBLIC_UMAMI_WEBSITE_ID: optionalString,
    NEXT_PUBLIC_UMAMI_SCRIPT: optionalUrl,
    // Analytics - OpenPanel
    NEXT_PUBLIC_OPENPANEL_CLIENT_ID: optionalString,
    // Analytics - Plausible
    NEXT_PUBLIC_PLAUSIBLE_DOMAIN: optionalString,
    NEXT_PUBLIC_PLAUSIBLE_SCRIPT: optionalUrl,
    // Analytics - Ahrefs
    NEXT_PUBLIC_AHREFS_WEBSITE_ID: optionalString,
    // Analytics - Seline
    NEXT_PUBLIC_SELINE_TOKEN: optionalString,
    // Analytics - DataFast
    NEXT_PUBLIC_DATAFAST_WEBSITE_ID: optionalString,
    NEXT_PUBLIC_DATAFAST_DOMAIN: optionalString,
    // Analytics - PostHog
    NEXT_PUBLIC_POSTHOG_KEY: optionalString,
    NEXT_PUBLIC_POSTHOG_HOST: optionalUrl,
    // Analytics - Clarity
    NEXT_PUBLIC_CLARITY_PROJECT_ID: optionalString,

    // Affiliate
    NEXT_PUBLIC_AFFILIATE_AFFONSO_ID: optionalString,
    NEXT_PUBLIC_AFFILIATE_PROMOTEKIT_ID: optionalString,

    // Captcha (Cloudflare Turnstile)
    NEXT_PUBLIC_TURNSTILE_SITE_KEY: optionalString,

    // Chatbox (Crisp)
    NEXT_PUBLIC_CRISP_WEBSITE_ID: optionalString,
  },
  runtimeEnv: {
    // Application
    NEXT_PUBLIC_BASE_URL: process.env.NEXT_PUBLIC_BASE_URL,
    NEXT_PUBLIC_PAYMENT_PROVIDER: process.env.NEXT_PUBLIC_PAYMENT_PROVIDER,

    // Payment - Stripe Prices
    NEXT_PUBLIC_STRIPE_PRICE_PRO_MONTHLY:
      process.env.NEXT_PUBLIC_STRIPE_PRICE_PRO_MONTHLY,
    NEXT_PUBLIC_STRIPE_PRICE_PRO_YEARLY:
      process.env.NEXT_PUBLIC_STRIPE_PRICE_PRO_YEARLY,
    NEXT_PUBLIC_STRIPE_PRICE_LIFETIME:
      process.env.NEXT_PUBLIC_STRIPE_PRICE_LIFETIME,
    NEXT_PUBLIC_STRIPE_PRICE_CREDITS_BASIC:
      process.env.NEXT_PUBLIC_STRIPE_PRICE_CREDITS_BASIC,
    NEXT_PUBLIC_STRIPE_PRICE_CREDITS_STANDARD:
      process.env.NEXT_PUBLIC_STRIPE_PRICE_CREDITS_STANDARD,
    NEXT_PUBLIC_STRIPE_PRICE_CREDITS_PREMIUM:
      process.env.NEXT_PUBLIC_STRIPE_PRICE_CREDITS_PREMIUM,
    NEXT_PUBLIC_STRIPE_PRICE_CREDITS_ENTERPRISE:
      process.env.NEXT_PUBLIC_STRIPE_PRICE_CREDITS_ENTERPRISE,

    // Payment - Creem Products
    NEXT_PUBLIC_CREEM_PRODUCT_PRO_MONTHLY:
      process.env.NEXT_PUBLIC_CREEM_PRODUCT_PRO_MONTHLY,
    NEXT_PUBLIC_CREEM_PRODUCT_PRO_YEARLY:
      process.env.NEXT_PUBLIC_CREEM_PRODUCT_PRO_YEARLY,
    NEXT_PUBLIC_CREEM_PRODUCT_LIFETIME:
      process.env.NEXT_PUBLIC_CREEM_PRODUCT_LIFETIME,
    NEXT_PUBLIC_CREEM_PRODUCT_CREDITS_BASIC:
      process.env.NEXT_PUBLIC_CREEM_PRODUCT_CREDITS_BASIC,
    NEXT_PUBLIC_CREEM_PRODUCT_CREDITS_STANDARD:
      process.env.NEXT_PUBLIC_CREEM_PRODUCT_CREDITS_STANDARD,
    NEXT_PUBLIC_CREEM_PRODUCT_CREDITS_PREMIUM:
      process.env.NEXT_PUBLIC_CREEM_PRODUCT_CREDITS_PREMIUM,
    NEXT_PUBLIC_CREEM_PRODUCT_CREDITS_ENTERPRISE:
      process.env.NEXT_PUBLIC_CREEM_PRODUCT_CREDITS_ENTERPRISE,

    // Feature Flags
    NEXT_PUBLIC_DEMO_WEBSITE: process.env.NEXT_PUBLIC_DEMO_WEBSITE,
    NEXT_PUBLIC_ENABLE_CREDITS: process.env.NEXT_PUBLIC_ENABLE_CREDITS,
    NEXT_PUBLIC_ENABLE_ANALYTICS_IN_DEV:
      process.env.NEXT_PUBLIC_ENABLE_ANALYTICS_IN_DEV,

    // Analytics
    NEXT_PUBLIC_GOOGLE_ANALYTICS_ID:
      process.env.NEXT_PUBLIC_GOOGLE_ANALYTICS_ID,
    NEXT_PUBLIC_UMAMI_WEBSITE_ID: process.env.NEXT_PUBLIC_UMAMI_WEBSITE_ID,
    NEXT_PUBLIC_UMAMI_SCRIPT: process.env.NEXT_PUBLIC_UMAMI_SCRIPT,
    NEXT_PUBLIC_OPENPANEL_CLIENT_ID:
      process.env.NEXT_PUBLIC_OPENPANEL_CLIENT_ID,
    NEXT_PUBLIC_PLAUSIBLE_DOMAIN: process.env.NEXT_PUBLIC_PLAUSIBLE_DOMAIN,
    NEXT_PUBLIC_PLAUSIBLE_SCRIPT: process.env.NEXT_PUBLIC_PLAUSIBLE_SCRIPT,
    NEXT_PUBLIC_AHREFS_WEBSITE_ID: process.env.NEXT_PUBLIC_AHREFS_WEBSITE_ID,
    NEXT_PUBLIC_SELINE_TOKEN: process.env.NEXT_PUBLIC_SELINE_TOKEN,
    NEXT_PUBLIC_DATAFAST_WEBSITE_ID:
      process.env.NEXT_PUBLIC_DATAFAST_WEBSITE_ID,
    NEXT_PUBLIC_DATAFAST_DOMAIN: process.env.NEXT_PUBLIC_DATAFAST_DOMAIN,
    NEXT_PUBLIC_POSTHOG_KEY: process.env.NEXT_PUBLIC_POSTHOG_KEY,
    NEXT_PUBLIC_POSTHOG_HOST: process.env.NEXT_PUBLIC_POSTHOG_HOST,
    NEXT_PUBLIC_CLARITY_PROJECT_ID: process.env.NEXT_PUBLIC_CLARITY_PROJECT_ID,

    // Affiliate
    NEXT_PUBLIC_AFFILIATE_AFFONSO_ID:
      process.env.NEXT_PUBLIC_AFFILIATE_AFFONSO_ID,
    NEXT_PUBLIC_AFFILIATE_PROMOTEKIT_ID:
      process.env.NEXT_PUBLIC_AFFILIATE_PROMOTEKIT_ID,

    // Captcha & Chatbox
    NEXT_PUBLIC_TURNSTILE_SITE_KEY: process.env.NEXT_PUBLIC_TURNSTILE_SITE_KEY,
    NEXT_PUBLIC_CRISP_WEBSITE_ID: process.env.NEXT_PUBLIC_CRISP_WEBSITE_ID,
  },
  skipValidation: process.env.SKIP_ENV_VALIDATION === 'true',
});
